### ISSUE TITLE
The page won't load and Discord links are dead

### ISSUE THREAD

**Issue by xNicklaj** [ricksouth/ntms.link#1]
As per title, you're missing a comma at the end of line 7 of https://github.com/ricksouth/ntms.link/blob/main/urls/shortened_urls.json, which makes it unable to load.

Also the links to the discord servers are invalid.

**Comment by ricksouth** [comment]
Thank you for letting me know! Edited it too quickly 😅

**Comment by xNicklaj** [comment]
So is the discord server closed completely?

**Comment by ricksouth** [comment]
Yes, unfortunately with my schedule I wasn't able to manage the Discord server or the messages sent. For the mods any questions for now go via the issue tracker on GitHub.
